name: Spec lint

on: [push]

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: lint-api-spec
        # uses: dangj/actions-test2@master
        uses: Fortellis/api-spec-lint-action@master
